###############################################################################
# Auto-generated by `jupyter-book config`
# If you wish to continue using _config.yml, make edits to that file and
# re-generate this one.
###############################################################################
author = "<a href='mailto:z.ma@mmu.ac.uk'>Dr Zhihua Ma</a>"
bibtex_bibfiles = ['references.bib']
comments_config = {'hypothesis': False, 'utterances': False}
copyright = '2023---2025'
exclude_patterns = ['**.ipynb_checkpoints', '.DS_Store', 'Thumbs.db', '_build']
extensions = ['sphinx_togglebutton', 'sphinx_copybutton', 'myst_nb', 'jupyter_book', 'sphinx_thebe', 'sphinx_comments', 'sphinx_external_toc', 'sphinx.ext.intersphinx', 'sphinx_design', 'sphinx_book_theme', 'sphinx_proof', 'sphinx_exercise', 'sphinxcontrib.tikz', 'sphinx_inline_tabs', 'sphinxcontrib.bibtex', 'sphinx_jupyterbook_latex']
external_toc_exclude_missing = True
external_toc_path = '_toc.yml'
hide_solutions = False
html_baseurl = ''
html_css_files = ['custom.css']
html_favicon = 'images/logo/odefavicon.png'
html_last_updated_fmt = '%A %d %B %Y %H:%M:%S'
html_logo = 'images/logo/logo1.svg'
html_show_copyright = True
html_sourcelink_suffix = ''
html_static_path = ['_static']
html_theme = 'sphinx_book_theme'
html_theme_options = {'navigation_with_keys': True, 'show_toc_level': 3, 'footer_start': ['sphinx-version'], 'footer_end': ['theme-version'], 'extra_footer': "<div>Powered by <a href='https://jupyterbook.org'>Jupyter Book</a></div>"}
html_title = 'Linear Multistep Methods'
language = 'en'
latex_elements = {'preamble': '\\usepackage{physics}'}
latex_engine = 'xelatex'
mathjax3_config = {'tex': {'macros': {'N': '\\mathbb{N}', 'Z': '\\mathbb{Z}', 'R': '\\mathbb{R}', 'C': '\\mathbb{C}', 'D': '\\mathrm{D}', 'E': '\\mathrm{E}', 'S': '\\mathrm{S}', 'dy': '\\mathrm{d}y', 'dx': '\\mathrm{d}x', 'ds': '\\mathrm{d}s', 'dt': '\\mathrm{d}t', 'i': '\\mathbf{\\hat{i}}', 'diff': ['\\frac{\\mathrm{d}^{#1}{#2}}{\\mathrm{d}{#3}^{#1}}', 3, ''], 'pdiff': ['\\frac{\\partial^{#1}{#2}}{\\partial{#3}^{#1}}', 3, '']}}}
mathjax_path = 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js'
myst_enable_extensions = ['amsmath', 'dollarmath', 'linkify', 'substitution', 'colon_fence', 'html_admonition', 'fieldlist', 'deflist']
myst_url_schemes = ['mailto', 'http', 'https']
nb_execution_allow_errors = False
nb_execution_cache_path = ''
nb_execution_excludepatterns = []
nb_execution_in_temp = False
nb_execution_mode = 'force'
nb_execution_timeout = 30
nb_output_stderr = 'show'
numfig = True
pygments_style = 'sphinx'
suppress_warnings = ['myst.domains']
use_jupyterbook_latex = True
use_multitoc_numbering = False
